#!/usr/bin/env Rscript
suppressPackageStartupMessages({library(httr2);library(jsonlite);library(digest)})
args<-commandArgs(trailingOnly=TRUE)
arg<-function(flag,default=NULL){i<-match(flag,args);if(is.na(i))return(default);if(i==length(args))stop(sprintf("Missing value after %s",flag),call.=FALSE);args[[i+1L]]}
pointer<-arg("--pointer");out<-arg("--output-dir")
if(is.null(pointer)||is.null(out)) stop("Required: --pointer --output-dir",call.=FALSE)
x<-fromJSON(pointer,simplifyVector=FALSE)
if(!identical(x$status,"published")||!identical(x$workflow,"03")||!identical(x$state,"publication_status")||!identical(x$visibility,"restricted")) stop("Invalid Workflow 03 pointer",call.=FALSE)
token<-Sys.getenv("ZENODO_ACCESS_TOKEN");if(!nzchar(token))stop("ZENODO_ACCESS_TOKEN required",call.=FALSE)
dep_id<-as.character(x$zenodo_deposition_id)
api<-paste0("https://zenodo.org/api/deposit/depositions/",dep_id)
auth<-function(req) req |> req_headers(Authorization=paste("Bearer",token))
dep<-request(api)|>auth()|>req_timeout(120)|>req_perform()|>resp_body_json(simplifyVector=FALSE)
if(!isTRUE(dep$submitted)) stop("Workflow 03 Zenodo deposition is not published",call.=FALSE)
bucket<-as.character(dep$links$bucket)
files<-x$archive_files
if(is.data.frame(files)) files<-lapply(seq_len(nrow(files)),function(i)as.list(files[i,,drop=FALSE]))
if(is.list(files)&&!is.null(files$filename)) files<-list(files)
archive_meta<-Filter(function(z) grepl("\\.tar\\.gz$",as.character(z$filename)),files)
if(length(archive_meta)!=1L) stop("Expected exactly one Workflow 03 state archive",call.=FALSE)
dir.create(out,recursive=TRUE,showWarnings=FALSE)
dl<-file.path(out,".download");dir.create(dl,showWarnings=FALSE)
z<-archive_meta[[1L]];fn<-as.character(z$filename);dest<-file.path(dl,fn)
resp<-request(paste0(sub("/$","",bucket),"/",URLencode(fn,reserved=TRUE)))|>req_method("GET")|>auth()|>req_timeout(1800)|>req_error(is_error=function(resp)FALSE)|>req_perform(path=dest)
if(resp_status(resp)!=200L) stop(sprintf("Download failed for %s",fn),call.=FALSE)
if(unname(file.info(dest)$size)!=as.numeric(z$bytes)) stop("Workflow 03 archive byte mismatch",call.=FALSE)
if(tolower(digest(file=dest,algo="sha256",serialize=FALSE))!=tolower(as.character(z$sha256))) stop("Workflow 03 archive SHA mismatch",call.=FALSE)
extract<-file.path(out,"extract");dir.create(extract,showWarnings=FALSE);utils::untar(dest,exdir=extract)
hits<-list.files(extract,pattern="^publication_status\\.jsonl$",recursive=TRUE,full.names=TRUE)
reports<-list.files(extract,pattern="^report\\.json$",recursive=TRUE,full.names=TRUE)
if(length(hits)!=1L||length(reports)!=1L) stop("Restored Workflow 03 archive has unexpected contents",call.=FALSE)
file.copy(hits[[1L]],file.path(out,"publication_status.jsonl"),overwrite=TRUE)
file.copy(reports[[1L]],file.path(out,"report.json"),overwrite=TRUE)
actual<-digest(file=file.path(out,"publication_status.jsonl"),algo="sha256",serialize=FALSE)
if(tolower(actual)!=tolower(as.character(x$publication_status_sha256))) stop("Workflow 03 publication-status SHA mismatch",call.=FALSE)
cat(sprintf("PASS: restored Workflow 03 publication-status layer; records=%d SHA256=%s\n",as.integer(x$records),actual))
