from pathlib import Path
p=Path('docs/index.html')
s=p.read_text(encoding='utf-8')
# Add DOI field to rendered records: build_dashboard.py supplies r.doi.
s=s.replace("'topics':alltopics}","'topics':alltopics,'doi':row.get(f['doi'],'') if f.get('doi') else ''}")
# Database controls: add topic selector and make headers sortable.
s=s.replace('<label>Country <select id="tableCountry"><option value="__all__">All countries</option></select></label><input id="topicFilter" readonly placeholder="Topic filter: none" style="min-width:280px">', '<label>Country <select id="tableCountry"><option value="__all__">All countries</option></select></label><label>Topic <select id="tableTopic"><option value="__all__">All topics</option></select></label>')
s=s.replace('<th>Record</th><th>Title</th><th>Year</th><th>Species</th><th>Country</th><th>Topics</th>', '<th data-sort="record_id">Record ↕</th><th data-sort="title">Title ↕</th><th data-sort="year">Year ↕</th><th data-sort="species">Species ↕</th><th data-sort="countries">Country ↕</th><th data-sort="topics">Topics ↕</th>')
# Replace filtering/table JS block with richer combined filtering, sorting and title links.
start=s.index('function recordsFor(r){')
end=s.index('function map(){',start)
new=r'''function recordsFor(){return D.records.filter(x=>(state.species==='__all__'||x.species.includes(state.species))&&(state.country==='__all__'||x.iso3.includes(state.country))&&(!state.topic||x.topics.includes(state.topic)||Object.values(x).filter(v=>Array.isArray(v)).flat().includes(state.topic))&&(!state.q||[x.record_id,x.title,x.abstract,x.year,...x.species,...x.countries,...x.topics].join(' ').toLowerCase().includes(state.q.toLowerCase())))}
function scholarUrl(title){const q=String(title||'').replace(/[^\p{L}\p{N}\s]/gu,'').trim().replace(/\s+/g,'+');return 'https://scholar.google.co.uk/scholar?hl=en&as_sdt=0%2C5&q='+q}
function recordUrl(r){return r.doi?'https://doi.org/'+encodeURIComponent(String(r.doi).replace(/^https?:\/\/(doi\.org\/)?/i,'')):scholarUrl(r.title)}
function table(){let a=recordsFor();const key=state.sort,dir=state.dir==='desc'?-1:1;a.sort((x,y)=>{const vx=key==='species'?x.species.join('; '):key==='countries'?x.countries.join('; '):key==='topics'?x.topics.join('; '):(x[key]??'');const vy=key==='species'?y.species.join('; '):key==='countries'?y.countries.join('; '):key==='topics'?y.topics.join('; '):(y[key]??'');return String(vx).localeCompare(String(vy),undefined,{numeric:true,sensitivity:'base'})*dir});const pages=Math.max(1,Math.ceil(a.length/state.size));state.page=Math.min(state.page,pages);const z=a.slice((state.page-1)*state.size,state.page*state.size);tbody.innerHTML=z.map(r=>`<tr><td class="muted">${esc(r.record_id)}</td><td><a href="${esc(recordUrl(r))}" target="_blank" rel="noopener"><b>${esc(r.title||'Untitled')}</b></a><div class="muted">${esc((r.abstract||'').slice(0,180))}</div></td><td>${esc(r.year)}</td><td>${r.species.filter(s=>s!=='Unspecified species').map(s=>`<button class="pill" data-species="${esc(s)}">${esc(s)}</button>`).join('')}</td><td>${r.countries.map(c=>`<button class="pill" data-country="${esc(c)}">${esc(c)}</button>`).join('')}</td><td>${r.topics.map(t=>`<button class="pill" data-topic="${esc(t)}">${esc(t)}</button>`).join('')}</td></tr>`).join('');document.querySelectorAll('[data-species]').forEach(b=>b.onclick=()=>setFilter({species:b.dataset.species}));document.querySelectorAll('[data-country]').forEach(b=>b.onclick=()=>setFilter({country:b.dataset.country}));document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>setFilter({topic:b.dataset.topic}));page.textContent=`${state.page} / ${pages} · ${fmt(a.length)} matching`;prev.disabled=state.page<=1;next.disabled=state.page>=pages}
'''
s=s[:start]+new+s[end:]
# Initialise topic selector and sorting state; make node/map interactions retain combined filters.
s=s.replace("let D,state={species:'__all__',country:'__all__',topic:null,q:'',page:1,size:50};", "let D,state={species:'__all__',country:'__all__',topic:null,q:'',page:1,size:50,sort:'title',dir:'asc'};")
s=s.replace("document.getElementById('topicFilter').value=state.topic?'Topic filter: '+state.topic:'Topic filter: none';", "if(document.getElementById('tableTopic')) document.getElementById('tableTopic').value=state.topic||'__all__';")
s=s.replace("const countries=Object.keys(D.country_iso3_counts||{});countries.forEach(c=>tableCountry.add(new Option(c,c)));", "const countries=Object.keys(D.country_iso3_counts||{});countries.forEach(c=>tableCountry.add(new Option(c,c)));Object.keys(D.topic_counts||{}).forEach(t=>tableTopic.add(new Option(t,t)));")
s=s.replace("tableCountry.onchange=()=>setFilter({country:tableCountry.value});q.oninput", "tableCountry.onchange=()=>setFilter({country:tableCountry.value});tableTopic.onchange=()=>setFilter({topic:tableTopic.value==='__all__'?null:tableTopic.value});document.querySelectorAll('th[data-sort]').forEach(th=>th.onclick=()=>{const k=th.dataset.sort;if(state.sort===k)state.dir=state.dir==='asc'?'desc':'asc';else{state.sort=k;state.dir='asc'}table()});q.oninput")
s=s.replace("clear.onclick=()=>setFilter({species:'__all__',country:'__all__',topic:null,q:''});", "clear.onclick=()=>setFilter({species:'__all__',country:'__all__',topic:null,q:''});")
p.write_text(s,encoding='utf-8')
print('Patched database links, combined filters, sorting and click-to-filter controls')
