#!/usr/bin/env python3
"""Replace the heatmap's flat level selector with a hierarchical drill-down."""
from pathlib import Path
P=Path('docs/index.html')
html=P.read_text(encoding='utf-8')
old='<label>Top-level topic <select id="heatTop"><option value="__all__">All topics</option></select></label><label>Topic level <select id="heatLevel"></select></label><label>Show <select id="heatLimit"><option>20</option><option selected>35</option><option>60</option></select></label>'
new='<label id="heat-old-top" style="display:none">Top-level topic <select id="heatTop"><option value="__all__">All topics</option></select></label><label id="heat-old-level" style="display:none">Topic level <select id="heatLevel"></select></label><label>Topic branch <select id="heatParent"><option value="__all__">All top-level topics</option></select></label><label>Show <select id="heatLimit"><option>10</option><option selected>20</option><option>35</option><option>60</option></select></label><button id="heatBack" type="button" style="display:none">Back one level</button>'
if old not in html: raise SystemExit('Heatmap controls pattern not found')
html=html.replace(old,new,1)
start=html.index('function heat(){')
end=html.index('function tree(){',start)
fn=r'''function heat(){const el=d3.select('#heatmap');el.selectAll('*').remove();const branch=heatParent.value||'__all__',limit=+heatLimit.value,all=D.species_group_topic_level_counts||D.species_topic_level_counts||{},species=heatSpecies.value==='__all__'?(D.species_display_order||Object.keys(D.species_counts)):[heatSpecies.value];let nodes=[];if(branch==='__all__'){nodes=Object.keys(D.topic_tree||{}).map(x=>({path:x,name:x}));}else{let node=D.topic_tree||{};for(const part of branch.split(' > '))node=node[part]?.children||{};nodes=Object.keys(node).map(name=>({path:branch+' > '+name,name}));}nodes.sort((a,b)=>a.name.localeCompare(b.name));nodes=nodes.slice(0,limit);const level=nodes.length?nodes[0].path.split(' > ').length:1,counts=all[String(level)]||{},cw=105,ch=34,left=210,bottom=250,w=Math.max(1000,left+nodes.length*cw+20),h=50+species.length*ch+bottom,svg=el.append('svg').attr('width',w).attr('height',h);const max=d3.max(species.flatMap(s=>nodes.map(n=>counts[`${s}|||${n.path}`]||0)))||1,color=d3.scaleSequential(d3.interpolateRgbBasis([palette[2],palette[1],palette[0],palette[5]])).domain([1,max]);species.forEach((s,i)=>nodes.forEach((n,j)=>{const v=counts[`${s}|||${n.path}`]||0;svg.append('rect').attr('x',left+j*cw).attr('y',40+i*ch).attr('width',cw).attr('height',ch).attr('fill',v===0?'#f8f9f8':color(v)).attr('class','heat-cell').on('click',()=>setFilter({species:s,topic:n.path})).on('mousemove',e=>showTip(e,`<b>${esc(s==='Unspecified species'?'Unspecified salmon':s)}</b><br>${esc(n.path)}<br>${fmt(v)} unique articles`)).on('mouseleave',hideTip)}));svg.selectAll('.slabel').data(species).join('text').attr('x',left-8).attr('y',(s,i)=>40+i*ch+22).attr('text-anchor','end').attr('class','axis').text(s=>s==='Unspecified species'?'Unspecified salmon':s);svg.selectAll('.tlabel').data(nodes).join('text').attr('transform',(n,i)=>`translate(${left+i*cw+cw/2},${40+species.length*ch+22}) rotate(-55)`).attr('text-anchor','end').attr('class','axis').text(n=>n.name.length>38?n.name.slice(0,36)+'…':n.name);heatBack.style.display=branch==='__all__'?'none':'inline-block';}
function configureHeat(){if(!window.D||!D.topic_tree||!document.getElementById('heatParent')){setTimeout(configureHeat,100);return}const sel=heatParent;sel.innerHTML='<option value="__all__">All top-level topics</option>';function add(obj,prefix=[]){Object.entries(obj||{}).sort((a,b)=>a[0].localeCompare(b[0])).forEach(([name,node])=>{const path=prefix.concat(name).join(' > ');const opt=new Option((prefix.length?'↳ ':'')+name,path);sel.appendChild(opt);if(Object.keys(node.children||{}).length)add(node.children,prefix.concat(name))})}add(D.topic_tree);sel.onchange=()=>heat();heatBack.onclick=()=>{const p=sel.value.split(' > ');p.pop();sel.value=p.length?p.join(' > '):'__all__';heat()};heat();}
'''
html=html[:start]+fn+html[end:]
html=html.replace('</script>','setTimeout(configureHeat,100);\n</script>',1)
P.write_text(html,encoding='utf-8')
print('Applied hierarchical heatmap drill-down')